# Generated by Django 5.0 on 2023-12-17 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_alter_personel_departman'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='departman',
            name='name',
            field=models.CharField(choices=[('FS', 'Fullstack'), ('FE', 'Frontend'), ('BE', 'Backend')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personel',
            name='title',
            field=models.CharField(choices=[('TL', 'Team Lead'), ('ML', 'Mid Lead'), ('J', 'Junior')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
